import { ClinicalCaseSummary, VitalsData, ClinicalHistorySections } from "@/types/clinical";
import { PatientProfile } from "@/types/patient";

export const mockPatients: PatientProfile[] = [
  {
    id: "pat-101",
    uhid: "AIIMS-2026-0941",
    abhaId: "91-4821-3920-1102",
    firstName: "Rajesh",
    lastName: "Gupta",
    fullName: "Rajesh Gupta",
    dateOfBirth: "1972-04-12",
    age: 54,
    gender: "Male",
    bloodGroup: "B+",
    contactPhone: "+91 98101 23456",
    emergencyContact: "+91 98101 98765 (Sunita Gupta, Wife)",
    district: "South Delhi",
    state: "Delhi",
    primaryCondition: "Type 2 Diabetes, Hypertension",
    riskCategory: "Moderate",
    totalEncounters: 6,
    lastVisitDate: "2026-09-14",
    allergiesSummary: ["Penicillin", "Sulfa drugs"],
  },
  {
    id: "pat-102",
    uhid: "AIIMS-2026-1024",
    abhaId: "44-1920-8841-3310",
    firstName: "Anita",
    lastName: "Verma",
    fullName: "Anita Verma",
    dateOfBirth: "1988-11-03",
    age: 37,
    gender: "Female",
    bloodGroup: "O+",
    contactPhone: "+91 94220 54321",
    emergencyContact: "+91 94220 99887 (Alok Verma, Husband)",
    district: "Gurugram",
    state: "Haryana",
    primaryCondition: "Bronchial Asthma",
    riskCategory: "High",
    totalEncounters: 4,
    lastVisitDate: "2026-09-14",
    allergiesSummary: ["Aspirin / NSAIDs"],
  },
  {
    id: "pat-103",
    uhid: "AIIMS-2026-0811",
    abhaId: "33-7721-0021-9943",
    firstName: "Sunil",
    lastName: "Deshmukh",
    fullName: "Sunil Deshmukh",
    dateOfBirth: "1960-08-25",
    age: 66,
    gender: "Male",
    bloodGroup: "A+",
    contactPhone: "+91 97110 44321",
    emergencyContact: "+91 97110 11223 (Son, Vikram)",
    district: "Noida",
    state: "Uttar Pradesh",
    primaryCondition: "Coronary Artery Disease (Post-PTCA)",
    riskCategory: "High",
    totalEncounters: 9,
    lastVisitDate: "2026-09-13",
    allergiesSummary: [],
  },
  {
    id: "pat-104",
    uhid: "AIIMS-2026-1189",
    abhaId: "12-6543-9812-7721",
    firstName: "Meenakshi",
    lastName: "Sundaram",
    fullName: "Meenakshi Sundaram",
    dateOfBirth: "1995-02-17",
    age: 31,
    gender: "Female",
    bloodGroup: "AB+",
    contactPhone: "+91 98840 77654",
    emergencyContact: "+91 98840 22110 (Mother, Lakshmi)",
    district: "South Delhi",
    state: "Delhi",
    primaryCondition: "Hypothyroidism",
    riskCategory: "Low",
    totalEncounters: 2,
    lastVisitDate: "2026-09-12",
    allergiesSummary: [],
  },
  {
    id: "pat-105",
    uhid: "AIIMS-2026-1250",
    abhaId: "77-3321-4455-9011",
    firstName: "Harpreet",
    lastName: "Singh",
    fullName: "Harpreet Singh",
    dateOfBirth: "1983-07-29",
    age: 43,
    gender: "Male",
    bloodGroup: "O-",
    contactPhone: "+91 98765 43210",
    emergencyContact: "+91 98765 01234 (Jasleen Kaur, Wife)",
    district: "West Delhi",
    state: "Delhi",
    primaryCondition: "Chronic Lumbar Radiculopathy",
    riskCategory: "Low",
    totalEncounters: 3,
    lastVisitDate: "2026-09-10",
    allergiesSummary: ["Ibuprofen"],
  },
];

export const mockCases: ClinicalCaseSummary[] = [
  {
    id: "case-2026-0041",
    caseNumber: "AR-2026-0041",
    patientId: "pat-101",
    patientName: "Rajesh Gupta",
    patientUhid: "AIIMS-2026-0941",
    patientAbha: "91-4821-3920-1102",
    patientAge: 54,
    patientGender: "Male",
    encounterType: "Outpatient General Medicine",
    encounterDate: "15 Sep 2026, 09:30",
    chiefComplaint: "Acute epigastric burning pain radiating to back for 2 days",
    status: "UNDER_REVIEW",
    severityLevel: "HIGH",
    authorName: "Sister Anjali Rao",
    authorRole: "Clinical Nurse Specialist",
    reviewerName: "Dr. Priya Sharma",
    lastUpdated: "12 mins ago",
    vitals: {
      systolic: 148,
      diastolic: 92,
      heartRate: 88,
      respiratoryRate: 18,
      temperature: 37.1,
      oxygenSat: 98,
      bloodGlucose: 164,
      recordedAt: "2026-09-15T09:35:00Z",
    },
    history: {
      presentingComplaint: "Severe epigastric burning pain and nausea for 48 hours.",
      historyOfPresentIllness:
        "54-year-old male presents with continuous sharp epigastric pain following heavy meal 2 days ago. Pain radiates posteriorly towards mid-thoracic spine. Mild relief on leaning forward. Associated with 2 episodes of non-bilious vomiting.",
      pastMedicalHistory: "Type 2 Diabetes Mellitus x 8 yrs, Essential Hypertension x 4 yrs.",
      pastSurgicalHistory: "Appendectomy (1998, uneventful).",
      drugHistory: "Tab Metformin 500mg BD, Tab Telmisartan 40mg OD.",
      allergyHistory: "Penicillin: Causes urticaria and facial puffiness.",
      familyHistory: "Father had acute myocardial infarction at age 62.",
      personalSocialHistory: "Non-smoker, occasional alcohol intake (social). Desk job, moderate stress.",
      aiStructured: true,
      aiModelUsed: "Arogya-Clinical-Structuring-v1",
      structuringConfidence: 0.94,
    },
  },
  {
    id: "case-2026-0042",
    caseNumber: "AR-2026-0042",
    patientId: "pat-102",
    patientName: "Anita Verma",
    patientUhid: "AIIMS-2026-1024",
    patientAbha: "44-1920-8841-3310",
    patientAge: 37,
    patientGender: "Female",
    encounterType: "Pulmonology Follow-up",
    encounterDate: "15 Sep 2026, 10:15",
    chiefComplaint: "Exertional dyspnea and nocturnal wheezing for 5 days",
    status: "UNDER_REVIEW",
    severityLevel: "CRITICAL",
    authorName: "Dr. Kabir Mehta",
    authorRole: "Junior Resident",
    reviewerName: "Dr. Priya Sharma",
    lastUpdated: "28 mins ago",
    vitals: {
      systolic: 122,
      diastolic: 78,
      heartRate: 104,
      respiratoryRate: 24,
      temperature: 36.8,
      oxygenSat: 93,
      recordedAt: "2026-09-15T10:20:00Z",
    },
    history: {
      presentingComplaint: "Worsening shortness of breath, tight chest and wheeze.",
      historyOfPresentIllness:
        "Known asthmatic presents with acute trigger following dust exposure. Inhaler frequency increased to 6 times daily with partial relief.",
      allergyHistory: "Aspirin induced bronchospasm reported in 2020.",
      aiStructured: true,
      structuringConfidence: 0.96,
    },
  },
  {
    id: "case-2026-0043",
    caseNumber: "AR-2026-0043",
    patientId: "pat-103",
    patientName: "Sunil Deshmukh",
    patientUhid: "AIIMS-2026-0811",
    patientAbha: "33-7721-0021-9943",
    patientAge: 66,
    patientGender: "Male",
    encounterType: "Cardiology Review",
    encounterDate: "15 Sep 2026, 08:45",
    chiefComplaint: "Routine post-angioplasty 6-month checkup, mild bilateral ankle edema",
    status: "FINALIZED",
    severityLevel: "MODERATE",
    authorName: "Dr. Priya Sharma",
    authorRole: "Attending Physician",
    reviewerName: "Dr. Priya Sharma",
    lastUpdated: "1 hour ago",
    vitals: {
      systolic: 134,
      diastolic: 84,
      heartRate: 68,
      respiratoryRate: 16,
      temperature: 36.6,
      oxygenSat: 99,
      recordedAt: "2026-09-15T08:50:00Z",
    },
  },
  {
    id: "case-2026-0044",
    caseNumber: "AR-2026-0044",
    patientId: "pat-104",
    patientName: "Meenakshi Sundaram",
    patientUhid: "AIIMS-2026-1189",
    patientAbha: "12-6543-9812-7721",
    patientAge: 31,
    patientGender: "Female",
    encounterType: "Endocrinology Intake",
    encounterDate: "15 Sep 2026, 11:00",
    chiefComplaint: "Generalized fatigue, mild weight gain and cold intolerance",
    status: "AI_STRUCTURED",
    severityLevel: "LOW",
    authorName: "Staff Nurse Pooja Rani",
    authorRole: "Triage Nurse",
    lastUpdated: "Just now",
    vitals: {
      systolic: 116,
      diastolic: 74,
      heartRate: 62,
      respiratoryRate: 14,
      temperature: 36.5,
      oxygenSat: 99,
      recordedAt: "2026-09-15T11:05:00Z",
    },
  },
  {
    id: "case-2026-0045",
    caseNumber: "AR-2026-0045",
    patientId: "pat-105",
    patientName: "Harpreet Singh",
    patientUhid: "AIIMS-2026-1250",
    patientAbha: "77-3321-4455-9011",
    patientAge: 43,
    patientGender: "Male",
    encounterType: "Orthopedics Consult",
    encounterDate: "14 Sep 2026, 16:30",
    chiefComplaint: "Low back pain with radiation down right posterior thigh (L5/S1)",
    status: "DRAFT",
    severityLevel: "LOW",
    authorName: "Sister Anjali Rao",
    authorRole: "Clinical Nurse Specialist",
    lastUpdated: "Yesterday",
  },
];

export const mockActivityTimeline = [
  {
    id: "act-1",
    title: "Clinical case signed and verified",
    timestamp: "15 Sep 2026, 09:12",
    description: "Dr. Priya Sharma approved final case record #AR-2026-0043 for Sunil Deshmukh. Digitally locked.",
    actor: "Dr. Priya Sharma",
    actorRole: "Attending Physician",
    status: "success" as const,
  },
  {
    id: "act-2",
    title: "AI structured intake ready for review",
    timestamp: "15 Sep 2026, 09:42",
    description: "Voice-assisted clinical narrative structured into 10 sections for case #AR-2026-0041.",
    actor: "Arogya AI Service",
    actorRole: "Assistive Structurer",
    status: "warning" as const,
  },
  {
    id: "act-3",
    title: "Allergy notification dispatched",
    timestamp: "15 Sep 2026, 10:22",
    description: "High-alert NSAID allergy flagged during Anita Verma history intake.",
    actor: "Clinical Triage Guard",
    actorRole: "Automated Check",
    status: "alert" as const,
  },
  {
    id: "act-4",
    title: "New patient registered",
    timestamp: "15 Sep 2026, 10:55",
    description: "Meenakshi Sundaram enrolled under UHID AIIMS-2026-1189 with verified ABHA credentials.",
    actor: "Staff Nurse Pooja Rani",
    actorRole: "Triage Nurse",
    status: "default" as const,
  },
];

export const mockMetrics = {
  activeEncounters: 14,
  pendingDoctorReviews: 3,
  finalizedCasesToday: 11,
  avgIntakeTimeMinutes: 4.2, // compared to standard 14 mins
  highRiskAlerts: 2,
};

